### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Gio345L** [Gio345L/STEC_dataset#1]
Search for following information on the resources:  

- https://www.cdc.gov/ecoli/surveillance.html 
- https://www.cdph.ca.gov/Programs/CID/DCDC/Pages/Shiga-toxin-producing-Escherichia-coli.aspx
- https://www.dhs.wisconsin.gov/publications/p4/p42158s.pdf
- https://www.youtube.com/watch?v=w-zbjM8wruk

1.- What is a STEC? 
STEC infection is an infection caused by certain Escherichia coli (E. coli) bacteria. 

1.1.- Any E.coli is an STEC?

2.- Why is a concern for human health?
Is a sanitation problem because Shiga toxin-producing E. coli, or "STEC" for short, produces a toxin (poison) that can make some people very sick. 

3.- Where STEC come from?
These bacteria are germs that naturally live in the intestines and feces (poop) of many animals, especially farm animals (such as cows, goats, and sheep) and deer. 

4.- How is correlated to Fresh produce?
Fresh produce can be infected with these bacteria so it should be cooked to the proper temperature to kill any microbes that can make you sick.

5.- What are the most common method of detection for STEC in fresh produce (ex. Romaine Lettuce, spinach, tango, etc)?

**Note**: Fresh produce refer to any fruit or vegetales know as "ready-to-eat" after harvesting without process.

Based on the answers, make a summary of STEC in fresh produce.

**Comment by RomanGomez** [comment]
1.-  STEC infection is an infection caused by certain Escherichia coli (E. coli) bacteria.
1.1.- no, not all E.coli are STEC, only those that have the ability to produce shiga toxin are considered STEC.
2.- Is a sanitation problem because Shiga toxin-producing E. coli, or "STEC" for short, produces a toxin (poison) that can make some people very sick.
3.- These bacteria are germs that naturally live in the intestines and feces (poop) of many animals, especially farm animals (such as cows, goats, and sheep) and deer.
4.- Fresh produce can be infected with these bacteria so it should be cooked to the proper temperature to kill any microbes that can make you sick.
5.- The California Department of Public Health (CDPH) and local health departments monitor cases of STEC infection because STEC can easily spread from person to person and can be spread through contaminated food and drinks that might be widely available. CDPH and local health departments monitor for outbreaks and investigate them to find a common source and take measures to prevent ongoing infections.

SUMMARY 
STEC are bacteria (E.coli) that can produce a toxin that is very dangerous to human health, these bacteria can normally spread in food for human consumption, if there is not a good sanitation control at the time of processing, packaging and distribution.

In addition, STEC can be transmitted to humans when food is contaminated with animal feces (cows, pigs) as well as human feces. When these foods are not properly washed or cooked, these bacteria can remain in the food and thus cause damage to the health of consumers. 

The main method of detection of STEC is through the health centers, they locate outbreaks of infections caused by these bacteria, then laboratory studies are made for the identification of these bacteria.

**Comment by Gio345L** [comment]
Sorry, i posted this comment before re-open the issue. 

Just dismiss this duplicate information.

**Comment by Gio345L** [comment]
Great job with your write-up!

I re-open this issue just to complement the information you provide.

Here are some corrections and suggestions to improve the clarity and readability:

1.- Shiga toxin-producing E. coli (STEC) is a group of E. coli bacteria that can cause STEC infections by producing a toxin called shiga toxin (stx) and an adhesion factor known as intimin (eae). Around 5-10% of those who are diagnosed with STEC infection develop a potentially life-threatening complication known as hemolytic uremic syndrome (HUS).

The principal STEC serovar linked to outbreak are know as Top 7 STEC: 

- E. coli O157:H7: "the jewel in the crown", the most common bacteria associated with outbreaks in the US
- E. coli O26
- E.coli O45
- E. coli O103
- E. coli O111
- E. coli O121
- E. coli O145

1.1.- No, not all strains of E. coli are harmful. Most strains are harmless, and only certain strains of E. coli, specifically the STEC group, are pathogenic and produce shiga toxin (stx) and intimin (eae).

2.- STEC is a sanitation problem that can make people sick when they ingest any product contaminated with the bacteria. The bacteria typically live in the intestines of healthy cattle, and contamination of their meat may occur during the slaughtering process. Infection most commonly occurs by eating contaminated food, particularly raw or undercooked meat. Infection can also occur after eating any product contaminated with STEC, including lettuce, alfalfa sprouts, salami, and raw (unpasteurized) milk, juice, or cider. Infected people can spread E. coli to others if they do not wash their hands after using the toilet.

3.-Shiga toxin-producing E. coli (STEC) can live in the intestines of healthy cattle and other animals, especially farm animals such as cows, goats, and sheep, as well as wildlife as deer. Other kinds of animals, including pigs and birds, can also pick up STEC from the environment and spread contamination to fields or facilities.

4.- Fresh produce can be exposed to fecal contamination through animal intrusion, contaminated food contact water (such as irrigation, washing, cleaning, etc.), environmental conditions such as flooding or dust exposure on fields, deficient Good Agricultural Practices (GAP) on fields or deficient Good Manufacturing Practices (GMP) in facilities, human manipulation with deficient hygiene, contaminated harvest/packing tools, deficient cleaning processes, and more.

5.- The most common methods for detecting STEC on fresh produce used by food laboratories include:

Cultural methods: Based on selective media and complemented by biochemical tests and serology (such as FDA/BAM methods, ISO methods, NOM methods, etc.). Turnaround time is long.
Serology methods: Based on the detection of specific antibodies (such as ELISA methods), which are limited in specificity and sensitivity. Turnaround time is medium to short.
Molecular methods: Based on DNA detection (such as PCR, MDA, TMA, RCA, SMART, NEAR, etc.) with target-specific sequences and high precision. The turnaround time is short.

**Now, what's next?**

Please complement your summary with the updated information provided in the answers. The goal is to help you understand what STEC is, how it affects the food supply chain, and the importance of having good methods of detection for it.

With this information, you'll be able to make more sense of the data in the dataset you're analyzing and figure out what questions and answers we can obtain from it.

Great job so far! Keep up the good work and move on to the next step.

**Comment by RomanGomez** [comment]
1.- Shiga toxin-producing E. coli (STEC) is a group of E. coli bacteria that can cause STEC infections by producing a toxin called shiga toxin (stx) and an adhesion factor known as intimin (eae). Around 5-10% of those who are diagnosed with STEC infection develop a potentially life-threatening complication known as hemolytic uremic syndrome (HUS).

The principal STEC serovar linked to outbreak are know as Top 7 STEC:

E. coli O157:H7: "the jewel in the crown", the most common bacteria associated with outbreaks in the US
E. coli O26
E.coli O45
E. coli O103
E. coli O111
E. coli O121
E. coli O145

1.1.- no, not all E.coli are STEC, only those that have the ability to produce shiga toxin are considered STEC.

2.- STEC is a sanitation problem that can make people sick when they ingest any product contaminated with the bacteria. The bacteria typically live in the intestines of healthy cattle, and contamination of their meat may occur during the slaughtering process. Infection most commonly occurs by eating contaminated food, particularly raw or undercooked meat. Infection can also occur after eating any product contaminated with STEC, including lettuce, alfalfa sprouts, salami, and raw (unpasteurized) milk, juice, or cider. Infected people can spread E. coli to others if they do not wash their hands after using the toilet.

3.-Shiga toxin-producing E. coli (STEC) can live in the intestines of healthy cattle and other animals, especially farm animals such as cows, goats, and sheep, as well as wildlife as deer. Other kinds of animals, including pigs and birds, can also pick up STEC from the environment and spread contamination to fields or facilities.

4.- Fresh produce can be exposed to fecal contamination through animal intrusion, contaminated food contact water (such as irrigation, washing, cleaning, etc.), environmental conditions such as flooding or dust exposure on fields, deficient Good Agricultural Practices (GAP) on fields or deficient Good Manufacturing Practices (GMP) in facilities, human manipulation with deficient hygiene, contaminated harvest/packing tools, deficient cleaning processes, and more.

5.- The most common methods for detecting STEC on fresh produce used by food laboratories include:

Cultural methods: Based on selective media and complemented by biochemical tests and serology (such as FDA/BAM methods, ISO methods, NOM methods, etc.). Turnaround time is long.
Serology methods: Based on the detection of specific antibodies (such as ELISA methods), which are limited in specificity and sensitivity. Turnaround time is medium to short.
Molecular methods: Based on DNA detection (such as PCR, MDA, TMA, RCA, SMART, NEAR, etc.) with target-specific sequences and high precision. The turnaround time is short.


SUMMARY
STEC are bacteria (E.coli) that can produce a toxin very dangerous to human health, these bacteria can spread normally in food intended for human consumption, if there is no good sanitary control at the time of processing, packaging and distribution.
The main strains of E.coli associated with this are as follows: 
E. coli O157:H7: "the jewel in the crown", the most common bacteria associated with outbreaks in the US
E. coli O26
E. coli O45
E. coli O103
E. coli O111
E. coli O121
E. coli O145

These bacteria are commonly found in the intestinal tract of animals such as cows, sheep and goats, and can contaminate meat, milk and agricultural products that have been in contact with animal manure, thus people who consume products with these characteristics can become infected with this bacterium.

Most people infected with STEC recover completely, but in severe cases they may experience complications including kidney damage, hemolytic anemia and neurological disorders. Young children, the elderly and people with weakened immune systems are at increased risk of developing serious complications.

Prevention of STEC infection includes proper hand washing, thorough cooking of meat, and consumption of pasteurized milk and juices. In case of suspected infection, it is important to seek immediate medical attention for treatment to prevent serious complications.

Finally, the main methods of detection of STEC are as follows:
Cultural methods: such as FDA/BAM methods, ISO methods, NOM methods, etc.). But the response time is long.
Serological methods: Based on detection of specific antibodies (such as ELISA methods), which are limited in specificity and sensitivity. Response time is medium to short.
Molecular methods: Based on DNA detection (such as PCR, MDA, TMA, TMA, RCA, SMART, NEAR, etc.) with target-specific sequences and high precision. Short turnaround time.

**Comment by Gio345L** [comment]
Hi,

Good work on the summary, just as observation to consider.

The summary aims to provide an overview of what STEC is, its characteristics, why it is concerning for human health, and the importance of detecting it. It's important to keep sentences short and avoid technical jargon as possible to ensure that even non-technical people can understand the information.

Below are some corrections and suggestions:

**Summary**

**Shiga toxin-producing E. coli (STEC)** is a group of E. coli bacteria that can cause STEC infections by producing a toxin called shiga toxin (encoded by the stx gene) and an adhesion factor known as intimin (encoded by the eae gene). These bacteria can live in the intestines of healthy cattle and other farm and wild animals.

STEC infections commonly occur by eating contaminated food, particularly raw or undercooked meat. Infection can also occur after consuming any product contaminated with STEC due to insanitary conditions and deficient Good Agricultural Practices (GAP) by fecal contamination, including fresh produce.

Most people infected with STEC recover completely. However, young children, the elderly, and people with weakened immune systems are at increased risk of developing serious complications. According to CDC, around 5-10% of those who are diagnosed with STEC infection develop a potentially life-threatening complication known as hemolytic uremic syndrome (HUS), that affects the kidneys and blood clotting functions.

The principal STEC serovars linked to outbreaks are known as the Top 7 STEC, which includes: E. coli O157:H7, O26, O45, O103, O111, O121, and O145.

Early detection of STEC in the food supply chain is crucial to prevent the introduction of contaminated food into the market, reducing the risk of an outbreak. The principal methods of detecting STEC in food are cultural methods, serological methods, and molecular methods.

Thank you
